### ISSUE TITLE
Remove debug message in files

### ISSUE THREAD

**Issue by bocian67** [bocian67/dezentrale_web#28]
Files are:
- blog_page.html (name of file as <p></p>)
- blog_index_page.html (like above)

**Comment by elbenfreund** [comment]
Can they be removed right away or does this issue depend on anything else?

**Comment by bocian67** [comment]
Yes, the debug messages can be removed now.

**Comment by elbenfreund** [comment]
This is solved in the recent PR right?

**Comment by bocian67** [comment]
solved here I think #27
