### ISSUE TITLE
Add reference to 'envdir' useage to install.rst

### ISSUE THREAD

**Issue by Rascat** [bocian67/dezentrale_web#29]
The install process of the project is not up to date. The following changes need be incorporated in the document (add points if incomplete):

- PostgreSQL is not used anymore. Delete section, add reference to sqlite3
- Add that envdir envs/dev is needed as prefix when executing makemigration or other commands

**Comment by elbenfreund** [comment]
In general ``PostgesSQL`` will probably be needed for the actual deployment, but it seems to make sense that we remove it for now as we do not yet know what the production environment will look like.
However, this is not related to the ``install.rst`` and should be handled separately.

**Comment by elbenfreund** [comment]
I had another look at the actual PR, and I no longer see the validity of this issue.
``installl.rst`` primarily deals with the installation of the resuluting package within a production environment
For consistency most of the required command steps should be handled as ``make`` targets. As such, no explicit reference to the details of ``envdir`` should be required. Looking at the suggessted PR, there seems to be a misunderstanding of what ``envdir envs/dev/ python manage.py makemigrations`` does and why it is not needed at all.

In case one uses the development setup, the postgres specific setup is simply not needed and one can continue with ``make migrate`` just as the current ``install.rst`` says.
In cases where prefixing ``envdir`` is actually needed (e.g. ``createsuperuser``) it is already made explicit.
