### ISSUE TITLE
Upgrade TextField to RichTextField

### ISSUE THREAD

**Issue by bocian67** [bocian67/dezentrale_web#30]
Upgrade TextField to RichTextField in blog_page

**Comment by elbenfreund** [comment]
What problem is to be solved by doing this?
For a broad discussion of the ramifications also please see [this blog post](https://torchbox.com/blog/rich-text-fields-and-faster-horses/).

**Comment by bocian67** [comment]
There is currently no problem, just as a 'Todo' it should be included as Issue. 
**It's not focused on being a RichTextField, it also can be a better solution**
