### ISSUE TITLE
auto-generation of slug [BlogPage]

### ISSUE THREAD

**Issue by bocian67** [bocian67/dezentrale_web#33]
Automatically generate the slug of Blog [/0; /1; /2; /3] instead of title [/title1; /title2; /anyTitle]

**Comment by elbenfreund** [comment]
Is there a particular reason for this? In general, "vocal" URLs are considered an industry best practice.

**Comment by bocian67** [comment]
IMHO it's better to use unique, calculated URLs, since two blog entrys could possibly have the same name, or any other reason, and this would make such scenarios easier.

**Comment by bocian67** [comment]
Should we use UIDs or the title?

**Comment by bocian67** [comment]
Agreed on just using the title in slug than in UIDs.
