### ISSUE TITLE
Remove 'pyenv' section from 'install.rst'

### ISSUE THREAD

**Issue by elbenfreund** [bocian67/dezentrale_web#39]
We will skip using ``pyenv`` for now. ``install.rst`` should be adjusted accordingly.

**Comment by shaniphankar** [comment]
Please refer to this and comment
https://github.com/shaniphankar/dezentrale_web/pull/2

**Comment by shaniphankar** [comment]
Please review it
https://github.com/bocian67/dezentrale_web/pull/43
