### ISSUE TITLE
Remove 'gitflow' section in 'install.rst'

### ISSUE THREAD

**Issue by elbenfreund** [bocian67/dezentrale_web#40]
For now we opt for a simpler ``feature branch`` branching model, as a consequence the section should be removed from the docs.

**Comment by shaniphankar** [comment]
Please examine and correct
https://github.com/shaniphankar/dezentrale_web/pull/1

**Comment by shaniphankar** [comment]
Please review it
https://github.com/bocian67/dezentrale_web/pull/42
